name: Build

on:
  workflow_dispatch:
    inputs:
      aseprite_version:
        description: 'The version of aseprite'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: download aseprite
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/aseprite/aseprite/releases/download/${{ inputs.aseprite_version }}/Aseprite-${{ inputs.aseprite_version }}-Source.zip -OutFile Aseprite.zip
          Expand-Archive -Path Aseprite.zip -DestinationPath C:\aseprite
      
      - name: download aseprite/skia (release m124)
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip -OutFile Skia.zip
          Expand-Archive -Path Skia.zip C:\Skia

      - name: install cmake & ninja
        shell: pwsh
        run: |
          winget install -e --id Kitware.CMake
          winget install Ninja-build.Ninja

      - name: setup vs dev env
        uses: seanmiddleditch/gha-setup-vsdevenv@v5
      
      - name: run cmake
        shell: push
        run: |
          cd C:\aseprite
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DLAF_BACKEND=skia -DSKIA_DIR=C:\Skia -DSKIA_LIBRARY_DIR=C:\Skia\out\Release-x64 -DSKIA_LIBRARY=C:\Skia\out\Release-x64\skia.lib -G Ninja ..
          ninja aseprite
      
      - name: clean up
        shell: pwsh
        run: |
          cd C:\aseprite\build\bin
          Remove-Item -Path "gen.exe" "gen.exe.manifest" "modp_b64_gen.exe" "modp_b64_gen.exe.manifest"
        
#      - name: make portable zip
#        shell: pwsh
#        run: |
#          cd C:\aseprite\build\bin
#          7z -tzip a Aseprite-Windows-Protable.zip *
      
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: C:\aseprite\build\bin
