name: Build

on:
  workflow_dispatch:
    inputs:
      aseprite_version:
        description: 'The version of aseprite'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

#      - name: install wget
#        run: |
#          choco install wget -y --no-progress

      - name: download aseprite
        run: |
          curl -o Aseprite.zip -L https://github.com/aseprite/aseprite/releases/download/v${{ inputs.aseprite_version }}/Aseprite-v${{ inputs.aseprite_version }}-Source.zip
          unzip Aseprite.zip -d aseprite
          mkdir -d aseprite/build
      
      - name: download aseprite/skia (release m124)
        run: |
          curl -o Skia.zip -L https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          unzip Skia.zip -d skia

#      - name: install cmake & ninja
#        run: |
#          winget install -e --id Kitware.CMake
#          winget install Ninja-build.Ninja

      - name: install ninja
        uses: aseprite/get-ninja@main

      - name: setup vs dev env
        uses: seanmiddleditch/gha-setup-vsdevenv@v5
      
      - name: run cmake
        working-directory: aseprite/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DLAF_BACKEND=skia -DSKIA_DIR=..\..\skia -DSKIA_LIBRARY_DIR=..\..\skia\out\Release-x64 -DSKIA_LIBRARY=..\..\skia\out\Release-x64\skia.lib -G Ninja ..
          ninja aseprite
      
      - name: clean up
        shell: cmd
        working-directory: aseprite/build
        run: |
          del gen.exe gen.exe.manifest modp_b64_gen.exe modp_b64_gen.exe.manifest
        
#      - name: make portable zip
#        run: |
#          cd aseprite\build\bin
#          7z -tzip a Aseprite-Windows-Protable.zip *
      
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: aseprite\build\bin
